homebrew_cask_packages:
  - { name: atom }
  - { name: sublime-text}
  - { name: google-chrome}
  - { name: firefox}
  - { name: karabiner-elements}
  - { name: android-studio}
  - { name: docker}
  - { name: sequel-pro}
  - { name: dropbox }
  - { name: skitch }
  - { name: clipy }
  - { name: the-unarchiver }
  - { name: vagrant }
  - { name: iterm2 }
  - { name: java }
  - { name: graphviz }
  - { name: xmind }
  - { name: font-ricty-diminished }
  - { name: slack }
  - { name: unity }
