- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  environment:
    HOMEBREW_CASK_OPTS: "--appdir=/Applications"
  vars_prompt:
    - name: "role_homebrew_packages"
      prompt: "install homebrew_packages?(yes/no)"
      private: no
      default: "no"
    - name: "role_homebrew_cask_packages"
      prompt: "install homebrew_cask_packages?(yes/no)"
      private: no
      default: "no"
    - name: "role_environment"
      prompt: "update environment?(yes/no)"
      private: no
      default: "no"
    # - name: "role_language"
    #   prompt: "update language?(yes/no)"
    #   private: no
    #   default: "no"
  roles:
    - { role: homebrew_packages, when: role_homebrew_packages == "yes" }
    - { role: homebrew_cask_packages, when: role_homebrew_cask_packages == "yes" }
    - { role: environment, when: role_environment == "yes" }
    # - { role: language, when: role_language == "yes" }
