- name: copy dotfiles
  copy: src=dotfiles dest=~/

- name: check /etc/shells
  shell: cat /etc/shells | grep /usr/local/bin/zsh | wc -l | tr -d ' '
  register: zsh_exist
  changed_when: false
  check_mode: no

- name: add zsh to /etc/shells
  shell: echo "/bin/zsh\n" >> /etc/shells
  when: zsh_exist.stdout == '0'
  become: yes

- name: check current shell
  shell: echo $SHELL
  register: current_shell
  changed_when: false
  check_mode: no

- name: change login shell to zsh
  shell: chsh -s /bin/zsh
  when: current_shell.stdout != "/bin/zsh"

- name: dotfiles install
  shell: ~/dotfiles/install.sh
