- name: brew tap homebrew_cask
  homebrew_tap: name=homebrew/cask state=present

- name: brew install packages --cask
  homebrew_cask:
    name: "{{ item.name }}"
    state: "{{ item.state|default('installed') }}"
    accept_external_apps: yes
  with_items: "{{ homebrew_cask_packages }}"
